In [ ]:
BFL >> 

Cost Function  MSE

In [ ]:
Residula > Ya - Yp
MSE = SSE /N

In [ ]:
SSE = sum(Ya - Yp)^2

In [ ]:
rmse  = np.sqrt(MSE)

## Mean Absolute Error

In [ ]:
MAE = sum(|Ya - Yp|)/N

MAE not prefered where outliers are prominant # because it penalize the outliers

## SST

## R squared

In [ ]:
R2 = 1  If all

## Advantages

In [2]:
import pandas as pd
df = pd.read_csv("autos_dataset.csv")
df.head().T

                             0            1            2      3      4
symboling                    3            3            1      2      2
normalized-losses            ?            ?            ?    164    164
make               alfa-romero  alfa-romero  alfa-romero   audi   audi
fuel-type                  gas          gas          gas    gas    gas
aspiration                 std          std          std    std    std
num-of-doors               two          two          two   four   four
body-style         convertible  convertible    hatchback  sedan  sedan
drive-wheels               rwd          rwd          rwd    fwd    4wd
engine-location          front        front        front  front  front
wheel-base                88.6         88.6         94.5   99.8   99.4
length                   168.8        168.8        171.2  176.6  176.6
width                     64.1         64.1         65.5   66.2   66.4
height                    48.8         48.8         52.4   54.3   54.3
curb-weight               2548         2548         2823   2337   2824
engine-type               dohc         dohc         ohcv    ohc    ohc
num-of-cylinders          four         four          six   four   five
engine-size                130          130          152    109    136
fuel-system               mpfi         mpfi         mpfi   mpfi   mpfi
bore                      3.47         3.47         2.68   3.19   3.19
stroke                    2.68         2.68         3.47    3.4    3.4
compression-ratio          9.0          9.0          9.0   10.0    8.0
horsepower                 111          111          154    102    115
peak-rpm                  5000         5000         5000   5500   5500
city-mpg                    21           21           19     24     18
highway-mpg                 27           27           26     30     22
price                    13495        16500        16500  13950  17450